name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        shell: sh
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Create File
        working-directory: .
        shell: sh
        run: |
          echo "This is a sample file created by the CI/CD pipeline" >>
          sample-file.txt
          git config --local user.email "samra.km16@gmail.com"
          git config --local user.name "samra16"
          git add sample-file.txt
          git commit -m "Add sample-file.txt"
          git push
