name: Create Test File
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Create File
        working-directory: .
        shell: sh
        run: |
          echo "This is a sample file created by the CI/CD pipeline" > sample1-file.txt
          git config --local user.email "samra.km16@gmail.com"
          git config --local user.name "samra16"
          git add .
          git commit -m "Add sample1-file.txt"
          git push origin main
