name: Display a File
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'read'
    steps:
      - uses: actions/checkout@v3
      - name: Display file content
        working-directory: .
        shell: sh
        run: |
          cat second2.sh

